---

- hosts: all
  become: true
  tasks:
  - name: install packages for CentOS/RedHat
    dnf:
      name: 
        - tmux
        - httpd
      state: latest
    when: ansible_distribution in ["CentOS", "RedHat"]
