---

- hosts: all
  become: true
  tasks:
 
  - name: Install packages for Each OS Distribution
    package:
      name: 
        - "{{ tmux_package }}"
        - "{{ apache_package }}"
      state: latest
      update_cache: yes         
