---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS/RedHat)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

- hosts: local
  become: true
  roles:
    - local

- hosts: server
  become: true
  roles:
    - server

- hosts: node
  become: true
  roles:
    - node
